name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t myapp:latest -f backend/Dockerfile .

    - name: Run containers in detached mode
      run: docker-compose up -d --build

    - name: Wait for app to be ready
      run: sleep 10

    - name: Test application availability
      run: curl --fail http://localhost:3000

    - name: Cleanup
      run: docker-compose down
